module.exports = {
  content: ["./frontend/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "cream-bg": "#FFFFFF",
        "muted-gray": "#6A7178",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#25694b",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002113",
        "surface-variant": "#e1e3df",
        "mustard-accent": "#D97706",
        "on-surface-variant": "#3f4943",
        "surface": "#f8faf6",
        "secondary": "#645d54",
        "outline-variant": "#bec9c0",
        "on-surface": "#191c1a",
        "primary-fixed-dim": "#90d5b0",
        "surface-container-highest": "#e1e3df",
        "secondary-fixed-dim": "#cfc5ba",
        "outline": "#6f7a72",
        "error": "#ba1a1a",
        "on-secondary-container": "#6a635a",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffcdb4",
        "on-secondary-fixed": "#201b14",
        "background": "#f8faf6",
        "error-container": "#ffdad6",
        "divider-line": "#E5E7E9",
        "primary": "#005135",
        "surface-container-high": "#e7e9e5",
        "on-secondary-fixed-variant": "#4c463d",
        "on-background": "#191c1a",
        "secondary-fixed": "#ebe1d5",
        "surface-container-low": "#f3f4f0",
        "inverse-primary": "#90d5b0",
        "on-tertiary-fixed-variant": "#763301",
        "primary-fixed": "#acf2cb",
        "tertiary-fixed-dim": "#ffb68e",
        "charcoal-text": "#191C1A",
        "surface-container": "#edeeeb",
        "on-secondary": "#ffffff",
        "tertiary-container": "#944918",
        "on-primary-fixed-variant": "#015236",
        "soft-terracotta": "#D97748",
        "inverse-surface": "#2e312f",
        "inverse-on-surface": "#f0f1ed",
        "surface-tint": "#266a4c",
        "surface-bright": "#f8faf6",
        "tertiary-fixed": "#ffdbca",
        "secondary-container": "#ebe1d5",
        "on-primary-container": "#a1e6c0",
        "tertiary": "#763200",
        "surface-dim": "#d9dad7",
        "forest-deep": "#0A5238",
        "on-tertiary-fixed": "#331200"
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "0.75rem",
        md: "0.875rem",
        lg: "1rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "32px",
        "stack-gap": "12px",
        "gutter": "16px",
        "touch-target-min": "48px",
        "unit": "8px",
        "section-gap": "32px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "label-sm": ["Noto Sans JP"],
        "body-md": ["Noto Sans JP"],
        "body-sm": ["Noto Sans JP"],
        "label-lg": ["Noto Sans JP"],
        "headline-sm": ["Noto Sans JP"],
        "body-lg": ["Noto Sans JP"],
        "headline-lg": ["Noto Sans JP"],
        "headline-lg-mobile": ["Noto Sans JP"],
        "headline-md": ["Noto Sans JP"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "800" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }]
      }
    }
  },
  plugins: []
};
